# Generated by Django 5.2.8 on 2025-11-21 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('estatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('masa_grasa', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('lesiones', models.TextField(blank=True, null=True)),
                ('cirugias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('suplementos', models.TextField(blank=True, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=255, null=True)),
                ('deporte', models.CharField(choices=[('tenis', 'Tenis'), ('boxeo', 'Boxeo'), ('gym', 'Gym'), ('yoga', 'Yoga'), ('running', 'Running'), ('natacion', 'Natación'), ('hyrox', 'Hyrox'), ('otros', 'Otros')], default='gym', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
