# Generated by Django 5.2.8 on 2025-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estatura',
            field=models.PositiveIntegerField(blank=True, help_text='Estatura en cm', null=True),
        ),
    ]
