# Generated by Django 5.2.8 on 2026-05-21 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_medicionfisica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InbodyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='inbody/')),
                ('fecha_test', models.DateField(help_text='Fecha del test InBody')),
                ('peso', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=4, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=1, help_text='kg, musculoesquelética', max_digits=5, null=True)),
                ('masa_grasa_kg', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, help_text='kg/m²', max_digits=4, null=True)),
                ('puntuacion_inbody', models.IntegerField(blank=True, help_text='/100', null=True)),
                ('tasa_metabolica_basal', models.IntegerField(blank=True, help_text='kcal', null=True)),
                ('agua_corporal', models.DecimalField(blank=True, decimal_places=1, help_text='L', max_digits=4, null=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbody_reports', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbody_reports_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_test', '-subido_en'],
            },
        ),
    ]
