# Generated by Django 5.2.8 on 2026-05-21 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_inbodyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbodyreport',
            name='archivo',
            field=models.FileField(upload_to='inbody/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
