# Generated by Django 5.2.8 on 2025-12-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_instructorprofile_progressreport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressReport',
        ),
    ]
