# Generated by Django 5.2.8 on 2026-02-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_progressreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='mi_instructor', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(limit_choices_to={'rol': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mis_clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
