# Generated by Django 5.2.8 on 2025-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_routinecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutassignment',
            name='calories',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='duration_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='reps',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='sets',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
