# Generated by Django 5.2.8 on 2025-12-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutassignment_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutassignment',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='workoutassignment',
            name='duration_min',
        ),
        migrations.RemoveField(
            model_name='workoutassignment',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutassignment',
            name='sets',
        ),
    ]
