# Generated by Django 5.2.8 on 2026-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutassignment_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='deporte',
            field=models.CharField(choices=[('gym', 'Gym'), ('futbol', 'Fútbol'), ('tenis', 'Tenis'), ('basketball', 'Basketball'), ('natacion', 'Natación'), ('ciclismo', 'Ciclismo'), ('boxeo', 'Boxeo'), ('yoga', 'Yoga'), ('running', 'Running'), ('voleibol', 'Voleibol'), ('beisbol', 'Béisbol'), ('atletismo', 'Atletismo'), ('pingpong', 'Ping Pong'), ('otro', 'Otro')], default='gym', max_length=20),
        ),
    ]
