# Generated by Django 5.2.8 on 2026-05-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_rutinacalendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(choices=[('fuerza', 'Fuerza'), ('funcional', 'Funcional'), ('potencia', 'Potencia'), ('casa', 'Ejercicios en casa')], default='fuerza', max_length=20),
        ),
    ]
