# Generated by Django 5.2.8 on 2026-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_ejercicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='grupo_indice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='grupo_tipo',
            field=models.CharField(choices=[('individual', 'Individual'), ('biserie', 'Biserie'), ('triserie', 'Triserie'), ('superserie', 'Superserie'), ('circuito', 'Circuito')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='intensidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='tiempo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='velocidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
