# Generated by Django 5.2.8 on 2026-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_rutinaejercicio_grupo_indice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(choices=[('fuerza', 'Fuerza'), ('funcional', 'Funcional'), ('potencia', 'Potencia'), ('casa', 'Ejercicios en casa'), ('estiramientos', 'Estiramientos')], default='fuerza', max_length=20),
        ),
    ]
